import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner'
import Header from '../components/common/header'
import './globals.css'
import './toggle.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bookstore',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[var(--color-background)] text-[var(--color-text)]`}
      >
        <Toaster position="top-right" />
        <Header />
        {children}
      </body>
    </html>
  )
}
