export const GENRES = [
  'Science',
  'Technology',
  'Literature',
  'Economics',
  'History',
  'Mystery',
  'Romance',
  'Fantasy',
  'Adventure',
  'Horror',
  'Biography',
  'Self-Help',
  'Cooking',
  'Travel',
  'Science Fiction',
  'Thriller',
  'Minimalism',
  'Software Development',
  'Web Development',
  'Algorithms',
  'Java Programming',
]

export const BOOK_LIST = [
  {
    id: 1,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    genre: 'Software Development',
  },
  {
    id: 2,
    title: 'JavaScript: The Good Parts',
    author: 'Douglas Crockford',
    genre: 'Web Development',
  },
  {
    id: 3,
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein',
    genre: 'Algorithms',
  },
  {
    id: 4,
    title: 'The Pragmatic Programmer: Your Journey to Mastery',
    author: 'Andrew Hunt, David Thomas',
    genre: 'Software Development',
  },
  {
    id: 5,
    title: 'Effective Java',
    author: 'Joshua Bloch',
    genre: 'Java Programming',
  },
]
